[env:esp32cam]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_AI_THINKER
    -DCONFIG_ESP32_SPIRAM_SUPPORT=1
    -mfix-esp32-psram-cache-issue

board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.f_cpu = 240000000L

upload_port = /dev/cu.usbserial-10
monitor_port = /dev/cu.usbserial-10
