[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DCAMERA_MODEL_AI_THINKER
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

extra_scripts = pre:version.py

board_build.flash_mode = dout
board_build.f_flash = 40000000L
board_build.f_cpu = 160000000L
board_build.partitions = partitions_ota.csv

upload_port = /dev/cu.usbserial-110
monitor_port = /dev/cu.usbserial-110

[env:esp32cam-ota]
extends = env:esp32cam
upload_protocol = espota
upload_port = 192.168.50.3
monitor_port = /dev/cu.usbserial-110
lib_deps =
    ArduinoJson @ 7.4.3
